# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    env:
      platform: gcp
      region: us-east-1
      account: 123456789
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASS }}
      
    runs-on: ubuntu-latest

    steps:
      - name: "Show message"
        run: echo "Hello world"

      - name: "Show ENV variables"
        if: ${{ env.platform == 'gcp' }}
        run: |
          echo "This is the value for cloud provider: ${{ env.platform }}"
          echo "This is the value for region: ${{ env.region }}"
          echo "This is the value for account: ${{ env.account }}"

          echo "This is the value for username: ${{ env.username }}"
          echo "This is the value for password: ${{ env.password }}"

      - name: "Show the values when the user is right"
        if: ${{ env.username != '' && env.password != '' }}
        run: |
          echo "Correct user ✅"
      
      - name: "Show variables by default"
        run: |
          echo "Event: ${{toJSON(github.event)}}"
          echo "Github_ACTOR: $GITHUB_ACTOR"
          echo "Github_ACTOR: $GITHUB_REPOSITORY"
